import type { DevStravaSession } from "./contract";

export const DEMO_USER = {
  id: "demo-user",
  email: "demo@devstrava.local",
  displayName: "Alex Rivera",
  handle: "alexrivera",
  city: "Bengaluru",
  region: "Karnataka",
  country: "IN",
} as const;

const session = (data: DevStravaSession): DevStravaSession => data;

export const DEMO_SESSIONS: DevStravaSession[] = [
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_01",
    startedAt: "2026-08-15T09:08:00Z",
    endedAt: "2026-08-15T10:50:00Z",
    activeDurationSeconds: 6120,
    coding: { manualPercent: 68, aiAssistedPercent: 24, automationPercent: 8, unknownBulkEditPercent: 0 },
    activity: { edits: 486, saves: 74, filesTouched: 12, linesChangedEstimate: 816 },
    terminal: { totalCommands: 18, build: 4, test: 6, git: 4, packageManager: 2, devServer: 1, lint: 1, other: 0 },
    ai: { claudeCodePrompts: 2, codexPrompts: 2, copilotPrompts: 7, tokenTotals: { claude: 2800, codex: 4100, copilot: 3600 } },
    reliability: { failures: 2, recoveredFailures: 2, recoveryRate: 100 },
    scores: { focus: 91, testingDiscipline: 84, recovery: 100, consistency: 86, aiBalance: 79, devScore: 902 },
    archetype: { primary: "Precision Coder", traits: ["Test-minded", "Measured AI", "Deep focus"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_02",
    startedAt: "2026-08-14T14:12:00Z",
    endedAt: "2026-08-14T16:25:00Z",
    activeDurationSeconds: 7980,
    coding: { manualPercent: 62, aiAssistedPercent: 31, automationPercent: 7, unknownBulkEditPercent: 0 },
    activity: { edits: 842, saves: 126, filesTouched: 18, linesChangedEstimate: 1342 },
    terminal: { totalCommands: 22, build: 7, test: 6, git: 5, packageManager: 2, devServer: 1, lint: 1, other: 0 },
    ai: { claudeCodePrompts: 8, codexPrompts: 4, copilotPrompts: 15, tokenTotals: { claude: 10000, codex: 9000, copilot: 9000 } },
    reliability: { failures: 5, recoveredFailures: 4, recoveryRate: 80 },
    scores: { focus: 82, testingDiscipline: 71, recovery: 80, consistency: 76, aiBalance: 68, devScore: 847 },
    archetype: { primary: "Vibe Coder", traits: ["Fast iteration", "AI heavy", "High recovery"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_03",
    startedAt: "2026-08-13T19:24:00Z",
    endedAt: "2026-08-13T21:36:00Z",
    activeDurationSeconds: 7920,
    coding: { manualPercent: 55, aiAssistedPercent: 21, automationPercent: 24, unknownBulkEditPercent: 0 },
    activity: { edits: 512, saves: 83, filesTouched: 9, linesChangedEstimate: 972 },
    terminal: { totalCommands: 31, build: 8, test: 7, git: 7, packageManager: 4, devServer: 2, lint: 2, other: 1 },
    ai: { claudeCodePrompts: 1, codexPrompts: 3, copilotPrompts: 6, tokenTotals: { claude: 1400, codex: 5100, copilot: 4200 } },
    reliability: { failures: 7, recoveredFailures: 6, recoveryRate: 86 },
    scores: { focus: 88, testingDiscipline: 92, recovery: 86, consistency: 80, aiBalance: 82, devScore: 875 },
    archetype: { primary: "Terminal Warrior", traits: ["Ship fast", "Command fluent", "Automation ready"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_04",
    startedAt: "2026-08-12T10:15:00Z",
    endedAt: "2026-08-12T11:03:00Z",
    activeDurationSeconds: 2880,
    coding: { manualPercent: 35, aiAssistedPercent: 57, automationPercent: 8, unknownBulkEditPercent: 0 },
    activity: { edits: 214, saves: 39, filesTouched: 6, linesChangedEstimate: 430 },
    terminal: { totalCommands: 9, build: 2, test: 2, git: 2, packageManager: 1, devServer: 1, lint: 1, other: 0 },
    ai: { claudeCodePrompts: 4, codexPrompts: 3, copilotPrompts: 5, tokenTotals: { claude: 5600, codex: 3900, copilot: 3200 } },
    reliability: { failures: 3, recoveredFailures: 2, recoveryRate: 67 },
    scores: { focus: 74, testingDiscipline: 65, recovery: 67, consistency: 70, aiBalance: 45, devScore: 734 },
    archetype: { primary: "Vibe Coder", traits: ["Explore widely", "Prompt fluent", "Rapid prototype"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_05",
    startedAt: "2026-08-11T07:20:00Z",
    endedAt: "2026-08-11T09:02:00Z",
    activeDurationSeconds: 6120,
    coding: { manualPercent: 72, aiAssistedPercent: 19, automationPercent: 9, unknownBulkEditPercent: 0 },
    activity: { edits: 366, saves: 58, filesTouched: 11, linesChangedEstimate: 704 },
    terminal: { totalCommands: 14, build: 4, test: 5, git: 3, packageManager: 1, devServer: 1, lint: 0, other: 0 },
    ai: { claudeCodePrompts: 1, codexPrompts: 1, copilotPrompts: 4, tokenTotals: { claude: 1200, codex: 1600, copilot: 2800 } },
    reliability: { failures: 1, recoveredFailures: 1, recoveryRate: 100 },
    scores: { focus: 94, testingDiscipline: 88, recovery: 100, consistency: 90, aiBalance: 88, devScore: 918 },
    archetype: { primary: "Precision Coder", traits: ["Early builder", "Steady hands", "Clean finish"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_06",
    startedAt: "2026-08-10T16:05:00Z",
    endedAt: "2026-08-10T18:17:00Z",
    activeDurationSeconds: 7320,
    coding: { manualPercent: 59, aiAssistedPercent: 28, automationPercent: 13, unknownBulkEditPercent: 0 },
    activity: { edits: 604, saves: 91, filesTouched: 15, linesChangedEstimate: 1102 },
    terminal: { totalCommands: 24, build: 5, test: 6, git: 6, packageManager: 3, devServer: 2, lint: 2, other: 0 },
    ai: { claudeCodePrompts: 3, codexPrompts: 4, copilotPrompts: 8, tokenTotals: { claude: 4600, codex: 7200, copilot: 6100 } },
    reliability: { failures: 4, recoveredFailures: 4, recoveryRate: 100 },
    scores: { focus: 86, testingDiscipline: 82, recovery: 100, consistency: 84, aiBalance: 73, devScore: 884 },
    archetype: { primary: "Ship Captain", traits: ["Strong cadence", "Reliable recovery", "Ships often"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_07",
    startedAt: "2026-08-09T22:05:00Z",
    endedAt: "2026-08-09T23:41:00Z",
    activeDurationSeconds: 5760,
    coding: { manualPercent: 48, aiAssistedPercent: 34, automationPercent: 18, unknownBulkEditPercent: 0 },
    activity: { edits: 298, saves: 47, filesTouched: 8, linesChangedEstimate: 521 },
    terminal: { totalCommands: 17, build: 3, test: 3, git: 5, packageManager: 2, devServer: 2, lint: 1, other: 1 },
    ai: { claudeCodePrompts: 3, codexPrompts: 2, copilotPrompts: 8, tokenTotals: { claude: 3900, codex: 2600, copilot: 5200 } },
    reliability: { failures: 4, recoveredFailures: 3, recoveryRate: 75 },
    scores: { focus: 79, testingDiscipline: 69, recovery: 75, consistency: 78, aiBalance: 61, devScore: 798 },
    archetype: { primary: "Night Owl", traits: ["Late sprint", "Creative flow", "Persistent"] },
  }),
  session({
    contract: "devstrava.session.v1",
    schemaVersion: 1,
    sessionId: "sess_demo_08",
    startedAt: "2026-08-08T11:30:00Z",
    endedAt: "2026-08-08T12:18:00Z",
    activeDurationSeconds: 2880,
    coding: { manualPercent: 64, aiAssistedPercent: 24, automationPercent: 12, unknownBulkEditPercent: 0 },
    activity: { edits: 201, saves: 31, filesTouched: 5, linesChangedEstimate: 366 },
    terminal: { totalCommands: 11, build: 2, test: 2, git: 4, packageManager: 1, devServer: 1, lint: 1, other: 0 },
    ai: { claudeCodePrompts: 1, codexPrompts: 1, copilotPrompts: 3, tokenTotals: { claude: 900, codex: 1300, copilot: 1900 } },
    reliability: { failures: 2, recoveredFailures: 2, recoveryRate: 100 },
    scores: { focus: 83, testingDiscipline: 76, recovery: 100, consistency: 82, aiBalance: 81, devScore: 832 },
    archetype: { primary: "Precision Coder", traits: ["Calm start", "Focused", "Test-minded"] },
  }),
];
