"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { toast } from "sonner";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowLeft, ArrowRight, BarChart3, Check, CheckCircle2, Cloud, Code2, Eye, EyeOff, Flame, HardDrive, LockKeyhole, Mail, ShieldCheck, Sparkles, Timer, Zap } from "lucide-react";
import { Brand, SprintlyMark } from "./brand";

type AuthMode="sign-in"|"create-account"|"forgot-password"|"verify-email"|"account-recovery";
const schema=z.object({email:z.string().email("Enter a valid email address"),password:z.string().min(8,"Use at least 8 characters").optional()});
type FormData=z.infer<typeof schema>;

const copy:Record<AuthMode,{title:string;desc:string;button:string}>={
  "sign-in":{title:"Welcome back.",desc:"Pick up where your last session left off.",button:"Sign in"},
  "create-account":{title:"Start your record.",desc:"Your local Sprintly data stays useful before sync.",button:"Create account"},
  "forgot-password":{title:"Reset your password.",desc:"We’ll send a secure recovery link to your inbox.",button:"Send reset link"},
  "verify-email":{title:"Check your inbox.",desc:"We sent a verification link to maya@example.com.",button:"Resend verification"},
  "account-recovery":{title:"Recover your account.",desc:"Use your account email to begin secure recovery.",button:"Start recovery"},
};

export function AuthScreen({mode}:{mode:AuthMode}){const [show,setShow]=useState(false);const router=useRouter();const c=copy[mode];const needsPassword=mode==="sign-in"||mode==="create-account";const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<FormData>({resolver:zodResolver(schema),defaultValues:{email:"",password:""}});const submit=async()=>{await new Promise(r=>setTimeout(r,500));toast.success(mode==="sign-in"?"Signed in to Sprintly":"Request sent",{description:"This interface is using the local product prototype."});router.push(mode==="create-account"?"/onboarding":"/app")};return <main className="grid min-h-dvh bg-[#090909] lg:grid-cols-[.92fr_1.08fr]"><section className="flex min-h-dvh flex-col px-5 py-5 sm:px-10 lg:px-14"><div className="flex items-center justify-between"><Brand/><Link href="/" className="inline-flex min-h-11 items-center gap-2 rounded-lg text-sm text-[#949494] hover:text-white"><ArrowLeft className="size-4"/> Back home</Link></div><div className="mx-auto flex w-full max-w-[420px] flex-1 flex-col justify-center py-12"><p className="mono text-[11px] uppercase tracking-[.18em] text-[#f2f2f2]">Sprintly account</p><h1 className="mt-4 text-3xl font-semibold tracking-[-.05em] sm:text-4xl">{c.title}</h1><p className="mt-3 text-sm leading-6 text-[#8b8b8b]">{c.desc}</p>
  {mode==="verify-email"?<div className="mt-8"><div className="grid min-h-[180px] place-items-center rounded-2xl border border-white/[.08] bg-white/[.025] text-center"><div><div className="mx-auto grid size-12 place-items-center rounded-xl bg-[#f2f2f2]/10 text-[#d2d2d2]"><Mail className="size-5"/></div><p className="mt-5 text-sm font-medium">Verification link sent</p><p className="mt-2 text-xs text-[#7d7d7d]">Link expires in 20 minutes.</p></div></div><button onClick={()=>toast.success("Verification email resent")} className="mt-4 min-h-12 w-full rounded-xl bg-[#f2f2f2] text-[#0b0b0b] text-sm font-semibold">{c.button}</button><Link href="/sign-in" className="mt-5 flex min-h-11 items-center justify-center text-sm text-[#c2c2c2]">Return to sign in</Link></div>:<form onSubmit={handleSubmit(submit)} className="mt-8 space-y-5" noValidate>
    {needsPassword&&<div className="grid grid-cols-2 gap-3"><button type="button" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/[.09] bg-white/[.025] text-sm text-[#cacaca] hover:bg-white/[.05]"><Code2 className="size-4"/> GitHub</button><button type="button" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-white/[.09] bg-white/[.025] text-sm text-[#cacaca] hover:bg-white/[.05]"><span className="mono text-sm font-bold">G</span> Google</button></div>}
    {needsPassword&&<div className="flex items-center gap-3 text-[10px] uppercase tracking-[.14em] text-[#666666]"><span className="h-px flex-1 bg-white/[.07]"/>or use email<span className="h-px flex-1 bg-white/[.07]"/></div>}
    <div><label htmlFor="email" className="text-xs font-medium text-[#bdbdbd]">Email address</label><input id="email" type="email" autoComplete="email" {...register("email")} aria-invalid={!!errors.email} aria-describedby={errors.email?"email-error":undefined} placeholder="you@example.com" className="mt-2 h-12 w-full rounded-xl border border-white/[.09] bg-white/[.025] px-3 text-sm outline-none placeholder:text-[#646464] focus:border-[#f2f2f2]"/>{errors.email&&<p id="email-error" role="alert" className="mt-2 text-xs text-[#aaaaaa]">{errors.email.message}</p>}</div>
    {needsPassword&&<div><div className="flex items-center justify-between"><label htmlFor="password" className="text-xs font-medium text-[#bdbdbd]">Password</label>{mode==="sign-in"&&<Link href="/forgot-password" className="text-xs text-[#c2c2c2]">Forgot password?</Link>}</div><div className="relative mt-2"><input id="password" type={show?"text":"password"} autoComplete={mode==="create-account"?"new-password":"current-password"} {...register("password")} aria-invalid={!!errors.password} aria-describedby={errors.password?"password-error":undefined} placeholder="At least 8 characters" className="h-12 w-full rounded-xl border border-white/[.09] bg-white/[.025] px-3 pr-12 text-sm outline-none placeholder:text-[#646464] focus:border-[#f2f2f2]"/><button type="button" onClick={()=>setShow(!show)} aria-label={show?"Hide password":"Show password"} className="absolute right-1 top-0 grid size-12 place-items-center text-[#7a7a7a]">{show?<EyeOff className="size-4"/>:<Eye className="size-4"/>}</button></div>{errors.password&&<p id="password-error" role="alert" className="mt-2 text-xs text-[#aaaaaa]">{errors.password.message}</p>}</div>}
    <button disabled={isSubmitting} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#f2f2f2] text-[#0b0b0b] text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50">{isSubmitting?"Working…":c.button}<ArrowRight className="size-4"/></button>
  </form>}
  {mode==="sign-in"&&<p className="mt-6 text-center text-sm text-[#7d7d7d]">New to Sprintly? <Link href="/create-account" className="font-medium text-[#d0d0d0]">Create an account</Link></p>}{mode==="create-account"&&<p className="mt-6 text-center text-sm text-[#7d7d7d]">Already have an account? <Link href="/sign-in" className="font-medium text-[#d0d0d0]">Sign in</Link></p>}
  <div className="mt-8 flex items-start gap-2 rounded-xl border border-[#d0d0d0]/15 bg-[#d0d0d0]/[.04] p-3"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[#d0d0d0]"/><p className="text-[11px] leading-5 text-[#838383]">Signing in connects selected extension data. It does not grant the website access to arbitrary local storage.</p></div></div></section>
  <aside className="relative hidden overflow-hidden border-l border-white/[.07] bg-[#0e0e0e] lg:block"><div className="absolute inset-0 bg-[radial-gradient(circle_at_60%_35%,rgba(128,128,128,.18),transparent_45%)]"/><div className="relative flex h-full flex-col justify-center p-16"><p className="mono text-xs uppercase tracking-[.18em] text-[#bdbdbd]">Your private record</p><h2 className="text-balance mt-5 max-w-xl text-5xl font-semibold leading-[1.05] tracking-[-.06em]">The work compounds. Now you can see it.</h2><div className="mt-12 grid max-w-xl grid-cols-2 gap-3">{[[Flame,"12 days","current streak"],[Timer,"18h 24m","focus this week"],[BarChart3,"+14%","week over week"],[LockKeyhole,"Local first","default state"]].map(([I,v,l])=>{const Icon=I as typeof Flame;return <div key={String(l)} className="rounded-2xl border border-white/[.08] bg-white/[.03] p-5"><Icon className="size-4 text-[#d2d2d2]"/><p className="mono mt-8 text-2xl font-semibold">{String(v)}</p><p className="mt-1 text-xs text-[#7a7a7a]">{String(l)}</p></div>})}</div></div></aside></main>}

const goals=[{icon:Flame,title:"Build consistency",desc:"Show up more often"},{icon:Timer,title:"Improve focus",desc:"Protect deep-work time"},{icon:Zap,title:"Maintain streaks",desc:"Keep momentum visible"},{icon:CheckCircle2,title:"Finish more tasks",desc:"Connect work to outcomes"}];
export function Onboarding(){const [step,setStep]=useState(1);const [selected,setSelected]=useState([0,1]);const [sync,setSync]=useState("Local only");const router=useRouter();const next=()=>step<5?setStep(step+1):router.push("/app");return <main className="noise min-h-dvh bg-[#090909]"><header className="flex h-16 items-center justify-between border-b border-white/[.07] px-4 sm:px-8"><Brand/><span className="mono text-xs text-[#797979]">STEP {step} / 5</span></header><div className="h-1 bg-white/[.04]"><motion.div animate={{width:`${step*20}%`}} className="h-full bg-gradient-to-r from-[#f2f2f2] to-[#bdbdbd]"/></div><section className="mx-auto flex min-h-[calc(100dvh-68px)] max-w-4xl flex-col px-4 py-10 sm:px-6 sm:py-16"><AnimatePresence mode="wait"><motion.div key={step} initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}} transition={{duration:.3}} className="flex flex-1 flex-col justify-center">
  {step===1&&<div className="text-center"><div className="mx-auto grid size-20 place-items-center rounded-[24px] border border-[#f2f2f2]/30 bg-[#f2f2f2]/10"><SprintlyMark className="size-11"/></div><p className="mono mt-8 text-xs uppercase tracking-[.2em] text-[#f2f2f2]">Welcome to Sprintly</p><h1 className="text-balance mx-auto mt-4 max-w-2xl text-4xl font-semibold tracking-[-.055em] sm:text-6xl">Let’s make the work visible.</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[#939393]">A private record of focus, consistency, and the developer you’re becoming.</p></div>}
  {step===2&&<div><p className="mono text-xs uppercase tracking-[.2em] text-[#bdbdbd]">Local-first by design</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Useful before the cloud.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[#939393]">The extension works independently and records only when you press start.</p><div className="mt-10 grid gap-3 md:grid-cols-3">{[[HardDrive,"Stored locally","Sessions live on your machine."],[Code2,"Aggregate signals","Activity counts, not source code."],[Cloud,"Sync by choice","Connect selected data later."]].map(([I,t,d])=>{const Icon=I as typeof HardDrive;return <div key={String(t)} className="panel p-5"><Icon className="size-5 text-[#d2d2d2]"/><h2 className="mt-8 text-base font-semibold">{String(t)}</h2><p className="mt-2 text-sm leading-6 text-[#838383]">{String(d)}</p></div>})}</div></div>}
  {step===3&&<div><p className="mono text-xs uppercase tracking-[.2em] text-[#f2f2f2]">Choose your direction</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">What should progress feel like?</h1><p className="mt-4 text-sm text-[#8b8b8b]">Choose one or more. You can change these anytime.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{goals.map(({icon:Icon,title,desc},i)=><button key={title} onClick={()=>setSelected(s=>s.includes(i)?s.filter(x=>x!==i):[...s,i])} aria-pressed={selected.includes(i)} className={`flex min-h-[100px] items-center gap-4 rounded-2xl border p-5 text-left transition ${selected.includes(i)?"border-[#f2f2f2]/50 bg-[#f2f2f2]/10":"border-white/[.08] bg-white/[.025] hover:bg-white/[.04]"}`}><div className={`grid size-11 place-items-center rounded-xl ${selected.includes(i)?"bg-[#f2f2f2] text-[#0b0b0b]":"bg-white/[.04]"}`}><Icon className="size-5"/></div><div><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-[#838383]">{desc}</p></div>{selected.includes(i)&&<Check className="ml-auto size-4 text-[#d0d0d0]"/>}</button>)}</div></div>}
  {step===4&&<div><p className="mono text-xs uppercase tracking-[.2em] text-[#bdbdbd]">Choose your boundary</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">How should Sprintly connect?</h1><p className="mt-4 text-sm text-[#8b8b8b]">Local-only is a complete experience. You can enable sync later.</p><div className="mt-9 space-y-3">{[[HardDrive,"Local only","Your activity stays on this device."],[Cloud,"Sync to Sprintly","Send selected activity to your account."],[Sparkles,"Decide later","Keep using the extension, no commitment."]].map(([I,t,d])=>{const Icon=I as typeof HardDrive;return <button key={String(t)} onClick={()=>setSync(String(t))} aria-pressed={sync===t} className={`flex min-h-[84px] w-full items-center gap-4 rounded-2xl border p-5 text-left transition ${sync===t?"border-[#f2f2f2]/50 bg-[#f2f2f2]/10":"border-white/[.08] bg-white/[.025]"}`}><Icon className="size-5 text-[#d2d2d2]"/><div><h2 className="text-sm font-semibold">{String(t)}</h2><p className="mt-1 text-xs text-[#838383]">{String(d)}</p></div><span className={`ml-auto grid size-5 place-items-center rounded-full border ${sync===t?"border-[#f2f2f2] bg-[#f2f2f2] text-[#0b0b0b]":"border-[#5b5b5b]"}`}>{sync===t&&<Check className="size-3"/>}</span></button>})}</div></div>}
  {step===5&&<div className="text-center"><div className="relative mx-auto size-28"><div className="grid size-28 place-items-center rounded-[32px] bg-gradient-to-br from-[#f2f2f2] to-[#bdbdbd] text-[#0b0b0b] text-2xl font-semibold">MR</div><div className="absolute -bottom-2 -right-2 grid size-10 place-items-center rounded-xl border-4 border-[#090909] bg-[#1a1a1a]"><Zap className="size-4 text-[#9a9a9a]"/></div></div><p className="mono mt-9 text-xs uppercase tracking-[.2em] text-[#d0d0d0]">Setup complete</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.055em] sm:text-5xl">Your journey starts local.</h1><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-[#8b8b8b]">Initial archetype: <span className="text-[#dbdbdb]">Steady Builder</span> · First goal: <span className="text-[#dbdbdb]">Build consistency</span> · Sync: <span className="text-[#dbdbdb]">{sync}</span></p><div className="mx-auto mt-8 flex max-w-lg items-center gap-3 rounded-xl border border-[#d0d0d0]/15 bg-[#d0d0d0]/[.04] p-4 text-left"><ShieldCheck className="size-5 shrink-0 text-[#d0d0d0]"/><p className="text-xs leading-5 text-[#858585]">Your boundary is saved. Sprintly will always show the state of your data.</p></div></div>}
  </motion.div></AnimatePresence><div className="mt-10 flex items-center justify-between"><button onClick={()=>setStep(Math.max(1,step-1))} disabled={step===1} className="inline-flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm text-[#8b8b8b] disabled:opacity-0"><ArrowLeft className="size-4"/> Back</button><button onClick={next} className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#f2f2f2] px-5 text-[#0b0b0b] text-sm font-semibold">{step===5?"Open Sprintly":"Continue"}<ArrowRight className="size-4"/></button></div></section></main>}
