"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import {
  Activity, ArrowRight, BarChart3, Check, EyeOff, Gauge, LockKeyhole,
  ShieldCheck, Trophy, Users,
} from "lucide-react";
import { PublicNav } from "./public-nav";
import { Brand } from "./brand";

const reveal = { initial: { opacity: 0, y: 18 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: "-70px" }, transition: { duration: .45 } };

function MarketingFooter() {
  return <footer className="border-t border-white/[.07] py-12"><div className="mx-auto flex max-w-[1240px] flex-col gap-6 px-4 sm:px-6 md:flex-row md:items-center md:justify-between"><div><Brand /><p className="mt-3 text-sm text-[#787878]">Private by default. Useful every day. Â© 2026 Sprintly.</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 text-sm text-[#939393]"><Link href="/">Home</Link><Link href="/how-it-works">How it works</Link><Link href="/pricing">Pricing</Link><Link href="/privacy">Privacy</Link><Link href="/app">Open Sprintly</Link></div></div></footer>;
}

const productSignals = [
  { icon: Gauge, title: "Focus signal", detail: "A readable view of time spent in a deliberate session." },
  { icon: BarChart3, title: "Work rhythm", detail: "Trends that show when your best work tends to happen." },
  { icon: Trophy, title: "Progress identity", detail: "Achievements grounded in consistency, not vanity metrics." },
];

export function ProductPage() {
  return <div className="noise min-h-dvh"><PublicNav /><main>
    <section className="border-b border-white/[.07] px-4 pb-24 pt-28 sm:px-6 sm:pt-36"><div className="mx-auto grid max-w-[1180px] gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><motion.div {...reveal}><p className="mono text-xs uppercase tracking-[.2em] text-[#bdbdbd]">The product surface</p><h1 className="text-balance mt-5 max-w-2xl text-4xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-6xl">A clear signal for the work nobody sees.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#999999]">Sprintly gives your coding sessions a shape you can return to: a quiet record of focus, rhythm, and progress.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/app" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#f2f2f2] px-5 text-sm font-semibold text-[#0b0b0b]">Open the live product <ArrowRight className="size-4" /></Link><Link href="/how-it-works" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-5 text-sm font-medium text-[#d6d6d6]">Follow the data path</Link></div></motion.div>
      <motion.div {...reveal} className="panel overflow-hidden p-4 sm:p-6"><div className="flex items-center gap-3 border-b border-white/[.07] pb-5"><span className="size-2 rounded-full bg-[#d0d0d0] shadow-[0_0_14px_rgba(210,210,210,.65)]" /><span className="text-sm font-medium">Today in Sprintly</span><span className="mono ml-auto text-[10px] text-[#737373]">LOCAL VIEW</span></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["2h 14m","focus time"],["87","focus score"],["12 days","current streak"]].map(([value,label])=><div key={label} className="rounded-xl border border-white/[.07] bg-white/[.025] p-4"><p className="mono text-2xl font-semibold tracking-[-.04em]">{value}</p><p className="mt-2 text-xs text-[#838383]">{label}</p></div>)}</div><div className="mt-3 rounded-xl border border-white/[.07] bg-[#0b0b0b] p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-medium">Focus across the week</p><p className="mt-1 text-xs text-[#777777]">A simple view of your last seven sessions</p></div><Activity className="size-4 text-[#a5a5a5]" /></div><div className="mt-8 flex h-28 items-end gap-2 sm:gap-3">{[42,68,54,82,61,94,74].map((height,index)=><div key={index} className="flex flex-1 flex-col items-center gap-2"><div className={`w-full rounded-t-sm ${index===5?"bg-[#f2f2f2]":"bg-[#656565]"}`} style={{height:`${height}%`}} /><span className="mono text-[9px] text-[#626262]">{["M","T","W","T","F","S","S"][index]}</span></div>)}</div></div></motion.div>
    </div></section>
    <section className="px-4 py-24 sm:px-6"><div className="mx-auto max-w-[1180px]"><motion.div {...reveal} className="max-w-2xl"><p className="mono text-xs uppercase tracking-[.2em] text-[#f2f2f2]">What you get</p><h2 className="text-balance mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-5xl">Useful depth without a louder dashboard.</h2><p className="mt-5 text-base leading-7 text-[#919191]">Each layer answers a different question, while the boundary around your code stays the same.</p></motion.div><div className="mt-12 grid gap-3 md:grid-cols-3">{productSignals.map(({icon:Icon,title,detail},index)=><motion.div key={title} {...reveal} transition={{delay:index*.06}} className="panel min-h-[240px] p-6"><Icon className="size-5 text-[#c6c6c6]" /><h3 className="mt-16 text-xl font-semibold tracking-[-.025em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#8c8c8c]">{detail}</p></motion.div>)}</div></div></section>
    <section className="border-y border-white/[.07] bg-[#0c0c0c] px-4 py-24 sm:px-6"><div className="mx-auto grid max-w-[1180px] gap-10 lg:grid-cols-[1fr_.9fr] lg:items-center"><motion.div {...reveal}><p className="mono text-xs uppercase tracking-[.2em] text-[#bdbdbd]">A deliberate boundary</p><h2 className="text-balance mt-4 max-w-xl text-3xl font-semibold tracking-[-.045em] sm:text-5xl">The product gets more useful without getting more invasive.</h2><p className="mt-5 max-w-xl leading-7 text-[#929292]">You choose when tracking starts, what can sync, and whether anything becomes public. Sprintly is built to make progress visible to you first.</p><Link href="/privacy" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[#d0d0d0]">Read the privacy model <ArrowRight className="size-4" /></Link></motion.div><motion.div {...reveal} className="grid gap-3">{[[EyeOff,"No source code","Aggregate activity only. Raw code and terminal content stay out of the record."],[LockKeyhole,"Local is complete","Sessions and review remain useful before an account or network connection."],[ShieldCheck,"Sharing is explicit","Synced data is not public data. Every shared surface has its own boundary."]].map(([Icon,title,detail])=>{const C=Icon as typeof EyeOff;return <div key={String(title)} className="flex gap-4 rounded-xl border border-white/[.07] bg-white/[.02] p-5"><C className="mt-0.5 size-5 shrink-0 text-[#c7c7c7]" /><div><p className="text-sm font-semibold">{String(title)}</p><p className="mt-2 text-sm leading-6 text-[#858585]">{String(detail)}</p></div></div>})}</motion.div></div></section>
    <section className="px-4 py-24 sm:px-6"><motion.div {...reveal} className="mx-auto max-w-[1180px] rounded-[20px] border border-[#f2f2f2]/25 bg-[#111111] p-8 sm:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="mono text-xs uppercase tracking-[.2em] text-[#8e8e8e]">Start with one session</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-.05em] sm:text-4xl">Your history can start locally.</h2></div><Link href="/app" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#f2f2f2] px-5 text-sm font-semibold text-[#0b0b0b]">Try Sprintly <ArrowRight className="size-4" /></Link></div></motion.div></section>
  </main><MarketingFooter /></div>;
}

const teamPrinciples = [
  { icon: Users, title: "Shared direction", detail: "Give a team a lightweight way to see momentum without turning personal activity into a manager scorecard." },
  { icon: ShieldCheck, title: "Privacy with teeth", detail: "Individual sessions stay individual. Team views use the slices people intentionally contribute." },
  { icon: BarChart3, title: "Better retros", detail: "Use real patterns to talk about capacity, focus, and sustainable pace in the next sprint." },
];

export function TeamsPage() {
  return <div className="noise min-h-dvh"><PublicNav /><main>
    <section className="border-b border-white/[.07] px-4 pb-24 pt-28 sm:px-6 sm:pt-36"><div className="mx-auto grid max-w-[1180px] gap-14 lg:grid-cols-[1fr_.9fr] lg:items-center"><motion.div {...reveal}><p className="mono text-xs uppercase tracking-[.2em] text-[#bdbdbd]">Sprintly for teams</p><h1 className="text-balance mt-5 max-w-2xl text-4xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-6xl">Make the team’s momentum easier to see.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#999999]">A shared layer for focused engineering groups, designed around consent, context, and a sustainable pace.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/pricing" className="inline-flex min-h-12 items-center gap-2 rounded-xl bg-[#f2f2f2] px-5 text-sm font-semibold text-[#0b0b0b]">See team plans <ArrowRight className="size-4" /></Link><Link href="/privacy" className="inline-flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-white/[.035] px-5 text-sm font-medium text-[#d6d6d6]">Our privacy model</Link></div></motion.div><motion.div {...reveal} className="panel p-4 sm:p-6"><div className="flex items-center justify-between border-b border-white/[.07] pb-5"><div><p className="text-sm font-medium">Team pulse</p><p className="mt-1 text-xs text-[#777777]">This week · shared metrics only</p></div><span className="rounded-full border border-[#d0d0d0]/25 bg-[#d0d0d0]/[.08] px-2.5 py-1 text-xs text-[#d0d0d0]">Opt-in</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><p className="mono text-2xl font-semibold">18h 42m</p><p className="mt-2 text-xs text-[#858585]">shared focus time</p></div><div className="rounded-xl border border-white/[.07] bg-white/[.02] p-4"><p className="mono text-2xl font-semibold">6 / 8</p><p className="mt-2 text-xs text-[#858585]">members contributing</p></div></div><div className="mt-3 space-y-3 rounded-xl border border-white/[.07] bg-[#0b0b0b] p-4"><div className="flex items-center justify-between text-xs"><span className="text-[#999999]">Sprint goal progress</span><span className="mono text-[#d0d0d0]">72%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.08]"><div className="h-full w-[72%] rounded-full bg-[#bdbdbd]" /></div><div className="flex items-center gap-2 pt-2 text-xs text-[#777777]"><ShieldCheck className="size-3.5 text-[#bdbdbd]" /> No individual rankings</div></div></motion.div></div></section>
    <section className="px-4 py-24 sm:px-6"><div className="mx-auto max-w-[1180px]"><motion.div {...reveal} className="max-w-2xl"><p className="mono text-xs uppercase tracking-[.2em] text-[#f2f2f2]">Built for healthy visibility</p><h2 className="text-balance mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-5xl">Team context, without individual surveillance.</h2></motion.div><div className="mt-12 grid gap-3 md:grid-cols-3">{teamPrinciples.map(({icon:Icon,title,detail},index)=><motion.div key={title} {...reveal} transition={{delay:index*.06}} className="panel min-h-[250px] p-6"><Icon className="size-5 text-[#c6c6c6]" /><h3 className="mt-16 text-xl font-semibold tracking-[-.025em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#8c8c8c]">{detail}</p></motion.div>)}</div></div></section>
    <section className="border-y border-white/[.07] bg-[#0c0c0c] px-4 py-24 sm:px-6"><div className="mx-auto max-w-[980px]"><motion.div {...reveal} className="text-center"><p className="mono text-xs uppercase tracking-[.2em] text-[#bdbdbd]">A calmer rollout</p><h2 className="text-balance mt-4 text-3xl font-semibold tracking-[-.045em] sm:text-5xl">Start with the team habits that matter.</h2><p className="mx-auto mt-5 max-w-2xl text-[#919191]">Teams can begin with a shared goal, add opt-in progress, and decide later whether a broader community layer is useful.</p></motion.div><div className="mt-12 grid gap-3 md:grid-cols-3">{[["01","Set a shared goal","Choose a sprint or focus theme everyone can understand."],["02","Contribute by choice","Members decide which aggregate signals belong in the team view."],["03","Review the pattern","Use the signal to improve planning, not to grade people."]].map(([step,title,detail])=><div key={step} className="rounded-xl border border-white/[.07] bg-white/[.02] p-5"><span className="mono text-xs text-[#bdbdbd]">{step}</span><h3 className="mt-10 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#858585]">{detail}</p></div>)}</div></div></section>
    <section className="px-4 py-24 sm:px-6"><motion.div {...reveal} className="mx-auto max-w-[1180px] overflow-hidden rounded-[20px] border border-[#f2f2f2]/25 bg-[#111111] p-8 sm:p-12"><div className="grid gap-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="mono text-xs uppercase tracking-[.2em] text-[#8e8e8e]">Coming soon</p><h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-.05em] sm:text-4xl">Bring Sprintly into your next retro.</h2><p className="mt-4 max-w-xl text-sm leading-6 text-[#919191]">Team features are being shaped around the same local-first boundary. Join the waitlist when you’re ready.</p></div><Link href="/pricing" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#f2f2f2] px-5 text-sm font-semibold text-[#0b0b0b]">View plans <ArrowRight className="size-4" /></Link></div></motion.div></section>
  </main><MarketingFooter /></div>;
}
